# -*- coding: utf-8 -*-
# Generated by the protocol buffer compiler.  DO NOT EDIT!
# source: protos/trip_updates.proto
"""Generated protocol buffer code."""
from google.protobuf.internal import builder as _builder
from google.protobuf import descriptor as _descriptor
from google.protobuf import descriptor_pool as _descriptor_pool
from google.protobuf import symbol_database as _symbol_database
# @@protoc_insertion_point(imports)

_sym_db = _symbol_database.Default()




DESCRIPTOR = _descriptor_pool.Default().AddSerializedFile(b'\n\x19protos/trip_updates.proto\"}\n\x0fVehiclePosition\x12\x12\n\nvehicle_id\x18\x01 \x01(\t\x12\x10\n\x08latitude\x18\x02 \x01(\x02\x12\x11\n\tlongitude\x18\x03 \x01(\x02\x12\x0f\n\x07\x62\x65\x61ring\x18\x04 \x01(\x02\x12\r\n\x05speed\x18\x05 \x01(\x02\x12\x11\n\ttimestamp\x18\x06 \x01(\x04\"7\n\x13VehiclePositionFeed\x12 \n\x06\x65ntity\x18\x01 \x03(\x0b\x32\x10.VehiclePositionb\x06proto3')

_builder.BuildMessageAndEnumDescriptors(DESCRIPTOR, globals())
_builder.BuildTopDescriptorsAndMessages(DESCRIPTOR, 'protos.trip_updates_pb2', globals())
if _descriptor._USE_C_DESCRIPTORS == False:

  DESCRIPTOR._options = None
  _VEHICLEPOSITION._serialized_start=29
  _VEHICLEPOSITION._serialized_end=154
  _VEHICLEPOSITIONFEED._serialized_start=156
  _VEHICLEPOSITIONFEED._serialized_end=211
# @@protoc_insertion_point(module_scope)
