# -*- coding: utf-8 -*-
# Generated by the protocol buffer compiler.  DO NOT EDIT!
# source: protos/vehicles.proto
"""Generated protocol buffer code."""
from google.protobuf.internal import builder as _builder
from google.protobuf import descriptor as _descriptor
from google.protobuf import descriptor_pool as _descriptor_pool
from google.protobuf import symbol_database as _symbol_database
# @@protoc_insertion_point(imports)

_sym_db = _symbol_database.Default()




DESCRIPTOR = _descriptor_pool.Default().AddSerializedFile(b'\n\x15protos/vehicles.proto\"]\n\x0fVehiclePosition\x12\x12\n\nvehicle_id\x18\x01 \x01(\t\x12\x10\n\x08latitude\x18\x02 \x01(\x02\x12\x11\n\tlongitude\x18\x03 \x01(\x02\x12\x11\n\ttimestamp\x18\x04 \x01(\x04\"/\n\x0b\x46\x65\x65\x64Message\x12 \n\x06\x65ntity\x18\x01 \x03(\x0b\x32\x10.VehiclePositionb\x06proto3')

_builder.BuildMessageAndEnumDescriptors(DESCRIPTOR, globals())
_builder.BuildTopDescriptorsAndMessages(DESCRIPTOR, 'protos.vehicles_pb2', globals())
if _descriptor._USE_C_DESCRIPTORS == False:

  DESCRIPTOR._options = None
  _VEHICLEPOSITION._serialized_start=25
  _VEHICLEPOSITION._serialized_end=118
  _FEEDMESSAGE._serialized_start=120
  _FEEDMESSAGE._serialized_end=167
# @@protoc_insertion_point(module_scope)
