# -*- coding: utf-8 -*-
# Generated by the protocol buffer compiler.  DO NOT EDIT!
# source: protos/vehicle_positions.proto
"""Generated protocol buffer code."""
from google.protobuf.internal import builder as _builder
from google.protobuf import descriptor as _descriptor
from google.protobuf import descriptor_pool as _descriptor_pool
from google.protobuf import symbol_database as _symbol_database
# @@protoc_insertion_point(imports)

_sym_db = _symbol_database.Default()




DESCRIPTOR = _descriptor_pool.Default().AddSerializedFile(b'\n\x1eprotos/vehicle_positions.proto\"]\n\x0fVehiclePosition\x12\x12\n\nvehicle_id\x18\x01 \x01(\t\x12\x10\n\x08latitude\x18\x02 \x01(\x02\x12\x11\n\tlongitude\x18\x03 \x01(\x02\x12\x11\n\ttimestamp\x18\x04 \x01(\x04\">\n\x1aVehiclePositionFeedMessage\x12 \n\x06\x65ntity\x18\x01 \x03(\x0b\x32\x10.VehiclePositionb\x06proto3')

_builder.BuildMessageAndEnumDescriptors(DESCRIPTOR, globals())
_builder.BuildTopDescriptorsAndMessages(DESCRIPTOR, 'protos.vehicle_positions_pb2', globals())
if _descriptor._USE_C_DESCRIPTORS == False:

  DESCRIPTOR._options = None
  _VEHICLEPOSITION._serialized_start=34
  _VEHICLEPOSITION._serialized_end=127
  _VEHICLEPOSITIONFEEDMESSAGE._serialized_start=129
  _VEHICLEPOSITIONFEEDMESSAGE._serialized_end=191
# @@protoc_insertion_point(module_scope)
